services:
  - type: web
    name: email-verifier-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: email-verifier-frontend
    env: static              # ✅ tells Render this is a static site
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
