services:
  - type: web
    name: email-verifier-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: email-verifier-frontend
    env: static                  # ✅ THIS IS THE MAGIC FIX
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
